# Generated by Django 5.1.4 on 2025-01-14 10:12

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='VPS',
            fields=[
                ('uid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='уникальный идентификатор сервера')),
                ('cpu', models.PositiveIntegerField(verbose_name='количество процессорных ядер')),
                ('ram', models.PositiveIntegerField(verbose_name='объем оперативной памяти')),
                ('hdd', models.PositiveIntegerField(verbose_name='объем дискового пространства')),
                ('status', models.CharField(choices=[('started', 'запущен'), ('blocked', 'заблокирован'), ('stopped', 'остановлен')], default='stopped', max_length=16, verbose_name='текущий статус сервера')),
            ],
            options={
                'verbose_name': 'сервер',
                'verbose_name_plural': 'Сервера',
            },
        ),
    ]
