# Generated by Django 5.1.4 on 2025-01-14 11:45

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vps', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vps',
            name='cpu',
            field=models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(32)], verbose_name='количество процессорных ядер'),
        ),
        migrations.AlterField(
            model_name='vps',
            name='hdd',
            field=models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(1048576)], verbose_name='объем дискового пространства'),
        ),
        migrations.AlterField(
            model_name='vps',
            name='ram',
            field=models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(131072)], verbose_name='объем оперативной памяти'),
        ),
    ]
